// Generates supabase/seed.sql from the frontend spot list so the database
// and the app share one source of truth. Run: node scripts/gen-seed.mjs
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const { SPOTS } = await import('../src/data/spots.ts')

const q = (v) => (v === undefined || v === null ? 'null' : `'${String(v).replace(/'/g, "''")}'`)
const n = (v) => (v === undefined || v === null ? 'null' : String(v))

const lines = SPOTS.map(
  (s) =>
    `(${q(s.id)}, ${q(s.nameKa)}, ${q(s.nameEn)}, ${q(s.type)}, ${q(s.region)}, ${n(s.lat)}, ${n(s.lon)}, ${q(s.depth)}, ` +
    `${q(JSON.stringify(s.species))}::jsonb, ${q(s.accessKa)}, ${q(s.accessEn)}, ${q(s.noteKa)}, ${q(s.noteEn)}, ` +
    `${s.infoOnly ? 'true' : 'false'}, ${n(s.feeGel)}, ${n(s.marineLat)}, ${n(s.marineLon)})`,
)

const sql = `-- Generated by web/scripts/gen-seed.mjs from web/src/data/spots.ts. Do not edit by hand.
insert into public.spots
  (id, name_ka, name_en, type, region, lat, lon, depth, species, access_ka, access_en, note_ka, note_en, info_only, fee_gel, marine_lat, marine_lon)
values
${lines.join(',\n')}
on conflict (id) do update set
  name_ka = excluded.name_ka,
  name_en = excluded.name_en,
  type = excluded.type,
  region = excluded.region,
  lat = excluded.lat,
  lon = excluded.lon,
  depth = excluded.depth,
  species = excluded.species,
  access_ka = excluded.access_ka,
  access_en = excluded.access_en,
  note_ka = excluded.note_ka,
  note_en = excluded.note_en,
  info_only = excluded.info_only,
  fee_gel = excluded.fee_gel,
  marine_lat = excluded.marine_lat,
  marine_lon = excluded.marine_lon;
`

const here = dirname(fileURLToPath(import.meta.url))
const out = resolve(here, '../../supabase/seed.sql')
writeFileSync(out, sql)
console.log(`wrote ${out} (${SPOTS.length} spots)`)
